#!/bin/bash

#we’ll be searching from this array a value
array=(1 2 3 4 5)

#this flag is to check the desire value is found or not
flag=0

pos=0

echo “Enter a value to search: ”
read a

for((i=0;i<5;i++))
do

if ((${array[$i]}==$a))
then


flag=`expr $[flag+1]`


pos=$i+1
break
fi
done

if (($flag==1))
then
printf “The current position of the value is: %d\n” $[pos]
else
echo “Not found”
fi
